clc;clear;
data = xlsread('data230k1.xlsx');
x = data(1:230400,2)';
y = data(1:230400,1)';
X = tonndata(x,true,false);
T = tonndata(y,true,false);
net = narxnet(1:2,1:2,50);
[x,xi,ai,t] = preparets(net,X,{},T);
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;
[net,tr] = train(net,x,t,xi,ai);
op = net(x,xi,ai);
e = gsubtract(t,op);
error = cell2mat(e);
output = cell2mat(op);
plot(y);
hold on;
plot(output);
plot(error);
legend('target','output','error');